# permissions to do viewer codimds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codimd-viewer-role
rules:
- apiGroups:
  - deploy.workshop.giantswarm.io
  resources:
  - codimds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.workshop.giantswarm.io
  resources:
  - codimds/status
  verbs:
  - get
